# api.mini-kbp.site → Django

<VirtualHost *:80>
    ServerName api.mini-kbp.site

    Include conf/extra/minikbp-common.conf

    RewriteEngine On

    ProxyPass /admin/ !
    RedirectMatch 404 ^/admin(/.*)?$

    ProxyPass / http://api:8000/ responsefieldsize=65536
    ProxyPassReverse / http://api:8000/

    ErrorLog /proc/self/fd/2
    CustomLog /proc/self/fd/1 combined
</VirtualHost>
