# Generated by Django 5.2.15 on 2026-06-25 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_grade'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupCurator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curators', to='academics.group', verbose_name='Группа')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curator_groups', to='accounts.teacher', verbose_name='Учитель')),
            ],
            options={
                'verbose_name': 'Куратор группы',
                'verbose_name_plural': 'Кураторы групп',
                'constraints': [models.UniqueConstraint(fields=('teacher', 'group'), name='uniq_group_curator')],
            },
        ),
        migrations.CreateModel(
            name='JournalDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('day_type', models.CharField(choices=[('normal', 'Обычный'), ('lab', 'Лабораторная работа'), ('okr', 'ОКР')], default='normal', max_length=16, verbose_name='Тип дня')),
                ('footer_note', models.CharField(blank=True, max_length=255, verbose_name='Пояснение (общий балл)')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_days', to='academics.teachingassignment', verbose_name='Назначение')),
            ],
            options={
                'verbose_name': 'День журнала',
                'verbose_name_plural': 'Дни журнала',
                'ordering': ['date'],
                'constraints': [models.UniqueConstraint(fields=('assignment', 'date'), name='uniq_journal_day_assignment_date')],
            },
        ),
        migrations.CreateModel(
            name='LatenessRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('minutes', models.PositiveSmallIntegerField(default=0, verbose_name='Минуты')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lateness_records', to='academics.group', verbose_name='Группа')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lateness_records', to='accounts.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Опоздание',
                'verbose_name_plural': 'Опоздания',
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('group', 'student', 'date'), name='uniq_lateness_group_student_date')],
            },
        ),
    ]
