# Generated by Django 5.2.10 on 2026-07-28 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_groupcurator_journalday_latenessrecord'),
        ('accounts', '0002_student_birth_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuratorInviteCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, verbose_name='Код')),
                ('expires_at', models.DateTimeField(verbose_name='Действует до')),
                ('max_uses', models.PositiveSmallIntegerField(default=10, verbose_name='Макс. использований')),
                ('use_count', models.PositiveSmallIntegerField(default=0, verbose_name='Использовано')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_codes_created', to='accounts.teacher', verbose_name='Создал')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_codes', to='academics.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Код куратора',
                'verbose_name_plural': 'Коды куратора',
                'constraints': [models.UniqueConstraint(fields=('group', 'code'), name='uniq_group_invite_code')],
            },
        ),
    ]
