# Generated by Django 5.2.15 on 2026-07-30 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_journalday_red_absent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['-date', 'slot', 'student__full_name'], 'verbose_name': 'Отметка', 'verbose_name_plural': 'Отметки'},
        ),
        migrations.AlterField(
            model_name='journalday',
            name='footer_note',
            field=models.CharField(blank=True, max_length=255, verbose_name='Пояснение к уроку'),
        ),
    ]
