# Generated by Django 5.2.10 on 2026-08-18 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0012_journalbackup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('grade_set', 'Отметка'), ('grade_delete', 'Удаление отметки'), ('day_meta', 'Мета дня'), ('lateness', 'Опоздание'), ('column_add', 'Добавление колонки'), ('column_delete', 'Удаление колонки')], max_length=32, verbose_name='Действие')),
                ('client_op_id', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='ID клиента')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Данные')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Актор')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='academics.teachingassignment', verbose_name='Назначение')),
            ],
            options={
                'verbose_name': 'Аудит журнала',
                'verbose_name_plural': 'Аудит журналов',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['assignment', '-created_at'], name='academics_j_assignm_631185_idx')],
            },
        ),
    ]
