# Generated by Django 5.2.10 on 2026-09-04 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0013_journal_audit_staff_security'),
    ]

    operations = [
        migrations.CreateModel(
            name='KbpGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kbp_id', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='ID kbp')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Группа kbp',
                'verbose_name_plural': 'Группы kbp',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='KbpPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kbp_id', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='ID kbp')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Аудитория kbp',
                'verbose_name_plural': 'Аудитории kbp',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='KbpSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kbp_id', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='ID kbp')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Предмет kbp',
                'verbose_name_plural': 'Предметы kbp',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='KbpTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kbp_id', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='ID kbp')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Преподаватель kbp',
                'verbose_name_plural': 'Преподаватели kbp',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='curatorinvitecode',
            name='kbp_teacher',
            field=models.ForeignKey(blank=True, help_text='При redeem teacher-кода привязывает Teacher к этому KbpTeacher.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invite_codes', to='academics.kbpteacher', verbose_name='Преподаватель kbp'),
        ),
        migrations.CreateModel(
            name='KbpTeachingLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='timetable', max_length=32, verbose_name='Источник')),
                ('last_seen_at', models.DateTimeField(auto_now=True, verbose_name='Последний раз в расписании')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_links', to='academics.kbpgroup', verbose_name='Группа')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_links', to='academics.kbpplace', verbose_name='Аудитория')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_links', to='academics.kbpsubject', verbose_name='Предмет')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_links', to='academics.kbpteacher', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Связь расписания kbp',
                'verbose_name_plural': 'Связи расписания kbp',
                'ordering': ['teacher', 'group', 'subject'],
                'constraints': [models.UniqueConstraint(fields=('teacher', 'group', 'subject'), name='uniq_kbp_teaching_link')],
            },
        ),
    ]
