# Generated by Django 5.2.10 on 2026-09-04 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0014_kbp_catalog_and_teacher_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplacementScanBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Дата')),
                ('day_of_week', models.CharField(blank=True, max_length=32, verbose_name='День недели')),
                ('signed_by', models.CharField(blank=True, max_length=255, verbose_name='Подпись')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликован')], db_index=True, default='draft', max_length=16, verbose_name='Статус')),
                ('ocr_meta', models.JSONField(blank=True, default=dict, verbose_name='OCR meta')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Опубликован')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_batches', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Пакет замен',
                'verbose_name_plural': 'Пакеты замен',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReplacementEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_code', models.CharField(db_index=True, max_length=64, verbose_name='Код группы')),
                ('lesson_number', models.PositiveSmallIntegerField(verbose_name='№ урока')),
                ('event_type', models.CharField(choices=[('NEW_LESSON', 'Новый урок'), ('CANCELLATION', 'Урок снят'), ('REPLACEMENT', 'Замена')], db_index=True, max_length=16, verbose_name='Тип')),
                ('replacement_data', models.JSONField(blank=True, default=dict, verbose_name='Новые данные')),
                ('original_data', models.JSONField(blank=True, default=dict, verbose_name='Было')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kbp_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_entries', to='academics.kbpgroup', verbose_name='Группа kbp')),
                ('kbp_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_entries', to='academics.kbpplace', verbose_name='Аудитория kbp')),
                ('kbp_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_entries', to='academics.kbpsubject', verbose_name='Предмет kbp')),
                ('kbp_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_entries', to='academics.kbpteacher', verbose_name='Преподаватель kbp')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='academics.replacementscanbatch', verbose_name='Пакет')),
            ],
            options={
                'verbose_name': 'Строка замены',
                'verbose_name_plural': 'Строки замен',
                'ordering': ['sort_order', 'id'],
                'indexes': [models.Index(fields=['batch', 'group_code', 'lesson_number'], name='academics_r_batch_i_3a10fe_idx')],
            },
        ),
    ]
