"""
Django settings for kbp_server project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import sys

from corsheaders.defaults import default_headers

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Публичный IP/VPS для доступа без домена (можно дополнить через DJANGO_ALLOWED_HOSTS).
DEPLOY_HOST = os.environ.get("APP_DEPLOY_HOST", "26.85.162.251").strip()
PUBLIC_URL = os.environ.get("APP_PUBLIC_URL", "").strip().rstrip("/")


def _origin_variants(host: str) -> list[str]:
    """http/https для одного хоста."""
    host = host.strip().rstrip("/")
    if not host:
        return []
    if host.startswith("http://") or host.startswith("https://"):
        base = host
        other = ("https://" + host[7:]) if host.startswith("http://") else ("http://" + host[8:])
        return [base, other]
    return [f"http://{host}", f"https://{host}"]


_MINIKBP_HOSTS = [
    "localhost",
    "127.0.0.1",
    "www.mini-kbp.site",
    "lk.mini-kbp.site",
    "panel.mini-kbp.site",
    "api.mini-kbp.site",
    "mini-kbp.site",
    DEPLOY_HOST,
]
_extra_hosts = [h.strip() for h in os.environ.get("DJANGO_ALLOWED_HOSTS", "").split(",") if h.strip()]
ALLOWED_HOSTS = list(_MINIKBP_HOSTS)
ALLOWED_HOSTS.extend(h for h in _extra_hosts if h not in ALLOWED_HOSTS)
if PUBLIC_URL:
    from urllib.parse import urlparse

    parsed = urlparse(PUBLIC_URL if "://" in PUBLIC_URL else f"https://{PUBLIC_URL}")
    if parsed.hostname and parsed.hostname not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(parsed.hostname)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

_RUNNING_TESTS = "test" in sys.argv

# SECURITY WARNING: keep the secret key used in production secret!
_DEV_FALLBACK_SECRET = (
    "django-insecure-a3*wp2%y4!5130g8+y1r9dknqz1ws+&54_cxtciv6h*xn13a_9"
)
_DEBUG_RAW = os.environ.get("DJANGO_DEBUG", "1" if _RUNNING_TESTS else "0")
DEBUG = _DEBUG_RAW.lower() in ("1", "true", "yes")

SECRET_KEY = (os.environ.get("DJANGO_SECRET_KEY") or "").strip()
if not SECRET_KEY:
    if DEBUG or _RUNNING_TESTS:
        SECRET_KEY = _DEV_FALLBACK_SECRET
    else:
        from django.core.exceptions import ImproperlyConfigured

        raise ImproperlyConfigured("DJANGO_SECRET_KEY is required when DJANGO_DEBUG=0")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # third-party
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',

    # local
    'accounts',
    'academics',
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "accounts.jwt_auth.SessionBoundJWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    "DEFAULT_RENDERER_CLASSES": (
        "rest_framework.renderers.JSONRenderer",
    ),
    "DEFAULT_THROTTLE_RATES": {
        "auth": "10000/minute" if _RUNNING_TESTS else "30/minute",
        "restore": "10000/hour" if _RUNNING_TESTS else "20/hour",
        "kbp_proxy": "10000/minute" if _RUNNING_TESTS else "120/minute",
    },
}

from datetime import timedelta  # noqa: E402

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=12),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "AUTH_HEADER_TYPES": ("Bearer",),
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'accounts.staff_lock_middleware.StaffSessionLockMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'kbp_server.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'kbp_server.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'Europe/Minsk'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS — для веб-приложения Next.js и Capacitor (origin https://localhost в APK)
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "https://localhost",  # Capacitor Android (bundled UI)
    "http://localhost",  # Capacitor / legacy
    "capacitor://localhost",  # Capacitor iOS
    "ionic://localhost",
    "minikbp://bundle",  # Electron local static UI
    "http://lk.mini-kbp.site",
    "http://panel.mini-kbp.site",
    "http://api.mini-kbp.site",
    "http://mini-kbp.site",
    "http://www.mini-kbp.site",
    "http://localhost.mini-kbp.site",
    "https://lk.mini-kbp.site",
    "https://panel.mini-kbp.site",
    "https://api.mini-kbp.site",
    "https://mini-kbp.site",
    "https://www.mini-kbp.site",
    "https://localhost.mini-kbp.site",
    f"http://{DEPLOY_HOST}",
    f"http://{DEPLOY_HOST}:3000",
    f"http://{DEPLOY_HOST}:8000",
    f"https://{DEPLOY_HOST}",
]
if PUBLIC_URL:
    CORS_ALLOWED_ORIGINS.extend(_origin_variants(PUBLIC_URL))
_extra_cors = [o.strip() for o in os.environ.get("DJANGO_CORS_ORIGINS", "").split(",") if o.strip()]
CORS_ALLOWED_ORIGINS.extend(o for o in _extra_cors if o not in CORS_ALLOWED_ORIGINS)
if not DEBUG:
    CORS_ALLOWED_ORIGINS = [
        o
        for o in CORS_ALLOWED_ORIGINS
        if o.startswith("https://")
        or o.startswith("http://localhost")
        or o.startswith("http://127.0.0.1")
        or o.startswith("capacitor://")
        or o.startswith("ionic://")
        or o.startswith("minikbp://")
    ]
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = (
    *default_headers,
    "x-client-kind",
    "x-mobile-bridge",
)

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://lk.mini-kbp.site",
    "http://panel.mini-kbp.site",
    "http://api.mini-kbp.site",
    "http://mini-kbp.site",
    "http://www.mini-kbp.site",
    "http://localhost.mini-kbp.site",
    "https://lk.mini-kbp.site",
    "https://panel.mini-kbp.site",
    "https://api.mini-kbp.site",
    "https://mini-kbp.site",
    "https://www.mini-kbp.site",
    "https://localhost.mini-kbp.site",
    f"http://{DEPLOY_HOST}",
    f"http://{DEPLOY_HOST}:3000",
    f"http://{DEPLOY_HOST}:8000",
    f"https://{DEPLOY_HOST}",
]
if PUBLIC_URL:
    CSRF_TRUSTED_ORIGINS.extend(_origin_variants(PUBLIC_URL))
_extra_csrf = [o.strip() for o in os.environ.get("DJANGO_CSRF_ORIGINS", "").split(",") if o.strip()]
CSRF_TRUSTED_ORIGINS.extend(o for o in _extra_csrf if o not in CSRF_TRUSTED_ORIGINS)
if not DEBUG:
    CSRF_TRUSTED_ORIGINS = [
        o
        for o in CSRF_TRUSTED_ORIGINS
        if o.startswith("https://")
        or o.startswith("http://localhost")
        or o.startswith("http://127.0.0.1")
    ]

SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = False
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SAMESITE = "Lax"
if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"

# Cloudflare Tunnel / reverse proxy
if PUBLIC_URL.startswith("https://") or os.environ.get("TRUST_PROXY_SSL", "").lower() in ("1", "true", "yes"):
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    USE_X_FORWARDED_HOST = True

# Email: Resend (предпочтительно), иначе Postfix/SMTP, иначе console
RESEND_API_KEY = os.environ.get("RESEND_API_KEY", "").strip()
_email_host = os.environ.get("EMAIL_HOST", "").strip()
if RESEND_API_KEY:
    EMAIL_BACKEND = os.environ.get(
        "EMAIL_BACKEND", "accounts.resend_backend.ResendEmailBackend"
    )
    DEFAULT_FROM_EMAIL = os.environ.get(
        "DEFAULT_FROM_EMAIL",
        os.environ.get("RESEND_FROM_EMAIL", "MiniKBP <onboarding@resend.dev>"),
    )
elif _email_host:
    EMAIL_BACKEND = os.environ.get(
        "EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend"
    )
    EMAIL_HOST = _email_host
    EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "587"))
    EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
    EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
    EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "1").lower() in ("1", "true", "yes")
    EMAIL_USE_SSL = os.environ.get("EMAIL_USE_SSL", "0").lower() in ("1", "true", "yes")
    DEFAULT_FROM_EMAIL = os.environ.get(
        "DEFAULT_FROM_EMAIL", "MiniKBP <noreply@mini-kbp.site>"
    )
else:
    EMAIL_BACKEND = os.environ.get(
        "EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend"
    )
    DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "noreply@minikbp.local")

APP_EMAIL_ENABLED = os.environ.get("APP_EMAIL_ENABLED", "").lower() in ("1", "true", "yes")
if RESEND_API_KEY:
    APP_EMAIL_ENABLED = True

FIREBASE_SERVICE_ACCOUNT_JSON = os.environ.get("FIREBASE_SERVICE_ACCOUNT_JSON", "").strip()
# Vision OCR for schedule replacement scans (OpenAI-compatible)
REPLACEMENT_VISION_API_KEY = os.environ.get("REPLACEMENT_VISION_API_KEY", "").strip()
REPLACEMENT_VISION_API_URL = os.environ.get("REPLACEMENT_VISION_API_URL", "https://api.openai.com/v1").strip()
REPLACEMENT_VISION_MODEL = os.environ.get("REPLACEMENT_VISION_MODEL", "gpt-4o-mini").strip()
APP_PUBLIC_URL = PUBLIC_URL

# Cookies lk / panel / api — всегда общий Domain, иначе panel.mini-kbp.site не видит вход с lk.
APP_COOKIE_DOMAIN = (os.environ.get("APP_COOKIE_DOMAIN") or ".mini-kbp.site").strip()
CSRF_COOKIE_DOMAIN = APP_COOKIE_DOMAIN or None
SESSION_COOKIE_DOMAIN = APP_COOKIE_DOMAIN or None

_redis_url = os.environ.get("REDIS_URL", "").strip()
_use_redis = False
if _redis_url:
    try:
        import django_redis  # noqa: F401
        _use_redis = True
    except ImportError:
        _use_redis = False

if _use_redis:
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": _redis_url,
            "OPTIONS": {"CLIENT_CLASS": "django_redis.client.DefaultClient"},
            "KEY_PREFIX": "minikbp",
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "minikbp-local",
        }
    }
