# Generated by Django 5.2.10 on 2026-07-28 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_curatorinvitecode'),
        ('accounts', '0002_student_birth_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email')),
                ('telegram_id', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Telegram ID')),
                ('telegram_username', models.CharField(blank=True, max_length=64, verbose_name='Telegram')),
                ('display_name', models.CharField(blank=True, max_length=255, verbose_name='Имя')),
                ('two_fa_enabled', models.BooleanField(default=False, verbose_name='2FA включена')),
                ('two_fa_secret', models.CharField(blank=True, max_length=64, verbose_name='2FA secret')),
                ('group_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Группа подтверждена')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_accounts', to='academics.group', verbose_name='Группа')),
                ('student', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_account', to='accounts.student')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='app_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Аккаунт приложения',
                'verbose_name_plural': 'Аккаунты приложения',
            },
        ),
    ]
