# Generated by Django 5.2.10 on 2026-07-28 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_appaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='appaccount',
            name='avatar_url',
            field=models.TextField(blank=True, verbose_name='Аватар'),
        ),
        migrations.AddField(
            model_name='appaccount',
            name='gender',
            field=models.CharField(blank=True, choices=[('', 'Не указан'), ('male', 'Мужской'), ('female', 'Женский'), ('other', 'Другой')], default='', max_length=16, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='appaccount',
            name='info',
            field=models.TextField(blank=True, verbose_name='О себе'),
        ),
        migrations.AddField(
            model_name='appaccount',
            name='nickname',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Никнейм'),
        ),
        migrations.AddField(
            model_name='appaccount',
            name='phone',
            field=models.CharField(blank=True, max_length=32, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='appaccount',
            name='referral_source',
            field=models.CharField(blank=True, max_length=64, verbose_name='Реферал'),
        ),
        migrations.AddField(
            model_name='appaccount',
            name='show_group',
            field=models.BooleanField(default=True, verbose_name='Показывать группу'),
        ),
    ]
