# Generated by Django 5.2.10 on 2026-07-28 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_appaccount_email_verified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='appaccount',
            name='profile_locked',
            field=models.BooleanField(default=False, verbose_name='Профиль заблокирован'),
        ),
        migrations.AddField(
            model_name='appaccount',
            name='profile_locked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Блокировка с'),
        ),
        migrations.AddField(
            model_name='appaccount',
            name='profile_locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_app_accounts', to='accounts.teacher', verbose_name='Заблокировал'),
        ),
        migrations.AddField(
            model_name='appaccount',
            name='session_ttl_days',
            field=models.PositiveSmallIntegerField(default=30, verbose_name='TTL сессии (дни)'),
        ),
        migrations.CreateModel(
            name='AppSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Ключ')),
                ('device_kind', models.CharField(choices=[('mobile', 'Мобильное'), ('web', 'Веб'), ('desktop', 'ПК')], default='web', max_length=16, verbose_name='Устройство')),
                ('user_agent', models.CharField(blank=True, max_length=512, verbose_name='User-Agent')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('trust_level', models.PositiveSmallIntegerField(default=1, verbose_name='Доверие')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(verbose_name='Истекает')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='Отозвана')),
                ('quick_login_token', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Быстрый вход')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='accounts.appaccount')),
            ],
            options={
                'verbose_name': 'Сессия приложения',
                'verbose_name_plural': 'Сессии приложения',
                'ordering': ['-last_seen'],
            },
        ),
    ]
