# Generated by Django 5.2.10 on 2026-08-18 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_pushdevice_account_platform'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushdevice',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='push_devices', to='accounts.appaccount'),
        ),
        migrations.CreateModel(
            name='StaffSecuritySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_hash', models.CharField(blank=True, max_length=128, verbose_name='PIN hash')),
                ('lock_enabled', models.BooleanField(default=False, verbose_name='Блокировка включена')),
                ('idle_lock_minutes', models.PositiveSmallIntegerField(default=5, verbose_name='Автоблокировка, мин')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_security', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Безопасность staff',
                'verbose_name_plural': 'Безопасность staff',
            },
        ),
        migrations.CreateModel(
            name='StaffSessionState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locked', models.BooleanField(default=False, verbose_name='Заблокирован')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Последняя активность')),
                ('unlock_push_token', models.CharField(blank=True, max_length=64, verbose_name='Push unlock token')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_session_state', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Состояние staff-сессии',
                'verbose_name_plural': 'Состояния staff-сессий',
            },
        ),
    ]
