# Generated by Django 5.2.11 on 2026-08-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_journal_audit_staff_security"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffsecuritysettings",
            name="pin_updated_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="PIN изменён"),
        ),
    ]
