# Generated by Django 5.2.10 on 2026-09-04 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0014_kbp_catalog_and_teacher_link'),
        ('accounts', '0011_staffsecuritysettings_pin_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='kbp_teacher',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_teacher', to='academics.kbpteacher', verbose_name='Преподаватель kbp'),
        ),
    ]
