# Generated by Django 5.2.10 on 2026-09-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_kbp_catalog_and_teacher_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushdevice',
            name='timetable_cat',
            field=models.CharField(blank=True, help_text='group|teacher|place|subject — последняя открытая сущность', max_length=32, verbose_name='Категория расписания'),
        ),
        migrations.AddField(
            model_name='pushdevice',
            name='timetable_entity_id',
            field=models.CharField(blank=True, max_length=64, verbose_name='ID сущности расписания'),
        ),
        migrations.AddField(
            model_name='pushdevice',
            name='timetable_entity_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Имя сущности расписания'),
        ),
    ]
